### ISSUE TITLE
Stream + Sink

### ISSUE THREAD

**Issue by mmstick** [imranmaj/websockets#1]
I need a way to both send and receive at the same time by fetching a stream and sink. Something like this:

```rust
let mut conn = WebSocket::connect(&url).await.unwrap();
let (sink, stream) = conn.duplex().split();

let conn_stream = stream! {
    while let Some(frame) = stream.next().await {
        // Return a frame for certain responses
        yield frame;
    }
};

// Combine frame responses from frames received through a channel
futures::stream::select(conn_stream, frame_receiver.into_stream())
    .forward(sink)
```

**Comment by imranmaj** [comment]
Hi, would [`tokio::select!`](https://docs.rs/tokio/0.2.22/tokio/macro.select.html) work for your use case? You can try multiple asynchronous tasks at the same time (in this case, `WebSocket::send` and `WebSocket::receive`).

**Comment by imranmaj** [comment]
I added support for this on the dev branch, where the WebSocket can be split into read and write halves. If you get a chance, could you please take a look at it (maybe clone it and cargo doc) and see if that's what you're looking for?

I'm still getting a mysterious UnexpectedEOF when receiving close frames, so I haven't merged/published to crates.io yet.

**Comment by mmstick** [comment]
Thanks! I will look into this tomorrow.

**Comment by mmstick** [comment]
Documentation states that the receive method on the read half will send frames back in response automatically. Is that still true for the split version?

**Comment by imranmaj** [comment]
In the split version, it should say that it will queue frames to be sent back automatically, but that they will not be sent until the write half is flushed (so not quite automatic). The write half can be flushed either by using the send method or by explicitly flushing with the flush method.

**Comment by mmstick** [comment]
Then this won't work for me. That would require multiple ownership of the sender. Is there a way to disable the automatic responses so that I can create my own stream which yields frames, so that I may combine it with a channel-based stream to make one stream that combines responses to the sender?

**Comment by imranmaj** [comment]
Could you please clarify why it would require the sender to have multiple owners?

**Comment by mmstick** [comment]
I'm updating an old crate that provides Phoenix Channel support for Rust, which was previously using the websocket crate, which is essentially a futures 0.1 variant of this. Phoenix channels simultaneously receive frames from a websocket connection, and forwards frames received from both an async Rust channel (`flume::Receiver`) and the read half of the connection to the write half of the connection.

Therefore, rather than having the crate assume that I want it to automatically submit frames on my behalf, I need to yield my own frames from the read half as its own stream, combine it with the async channel's stream, and forward all frames from both streams to the write half. It's not possible to do it with this API.

This solution requires multiple ownership because I would need the receiving stream to also flush and send frames, while also needing a second ownership of the writer to send frames from the channel.

**Comment by imranmaj** [comment]
I can add a method to the receiver to receive frames without automatically queueing frames to be sent, would that work?

**Comment by mmstick** [comment]
Yes, that would work

**Comment by imranmaj** [comment]
Should be done per d34147bd225d88115d3d7339e2ede5f26acb7fc4, tell me if it looks good and I'll publish

**Comment by imranmaj** [comment]
Merged and published to crates.io as version 0.1.6
