### ISSUE TITLE
Non-default SSL circumstances

### ISSUE THREAD

**Issue by thsioutas** [imranmaj/websockets#2]
I think it would be a good idea to be able to use non-default SSL configuration as a parameter to the connect function similar to: https://docs.rs/websocket/0.26.2/websocket/client/builder/struct.ClientBuilder.html#method.connect
What do you think? I could open a PR for this.

**Comment by imranmaj** [comment]
Yes, that's a good idea. I'm trying to keep the API as simple as possible, so I think it would be a good idea to

1. Make the `WebSocketBuilder` store a [`TlsConnectorBuilder`](https://docs.rs/native-tls/0.2.5/native_tls/struct.TlsConnectorBuilder.html) internally
2. Create wrapper methods on the `WebSocketBuilder` around the `TlsConnectorBuilder` methods, and make the `connect` method use the `TlsConnectorBuilder` to establish the secure connection
3. Re-export the [`Certificate`](https://docs.rs/native-tls/0.2.5/native_tls/struct.Certificate.html), [`Protocol`](https://docs.rs/native-tls/0.2.5/native_tls/enum.Protocol.html), and [`Identity`](https://docs.rs/native-tls/0.2.5/native_tls/struct.Identity.html) from [`native-tls`](https://docs.rs/native-tls/) in a module called `secure` or something similar

That way this crate would not have doc links to other crates, which can be pretty confusing for people who are just trying to get a simple WebSocket set up IMO (and those people are really who this crate is targeting).

I was planning on doing this already but I'm a little busy right now, so it would take me a few weeks to get around to it. Pull requests are very welcome, but as I mentioned, I will probably do it in a few weeks if you don't get a chance to. Please also let me know if you have other suggestions about how to approach this.

**Comment by imranmaj** [comment]
Ah, I just noticed your pull request. Thank you for submitting it; I appreciate your help. However, I do think it would be better to change the builder instead of the connect method.

**Comment by thsioutas** [comment]
Opened a new one :)

**Comment by stefos-pd** [comment]
Hi,

I would like to have this issue resolved as well, is there an update on the current PR?

**Comment by imranmaj** [comment]
I apologize for the delay. It is now on crates.io as version 0.2.0.

@thsioutas feel free to close this issue unless there is something else that needs changing.
