### ISSUE TITLE
Doesn't he support the use of proxies?

### ISSUE THREAD

**Issue by 86maid** [imranmaj/websockets#8]
It seems that using the following instruction is not valid

export https_proxy=http://127.0.0.1:7890; export http_proxy=http://127.0.0.1:7890; export all_proxy=socks5://127.0.0.1:7890

**Comment by imranmaj** [comment]
Proxies are not supported at this time

**Comment by 86maid** [comment]
When will it be updated?












xchuang233
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Dec 14, 2023 23:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [imranmaj/websockets] Doesn't he support the use of proxies?(Issue #8)




 
Proxies are not supported at this time

**Comment by imranmaj** [comment]
There are currently no plans to support proxies. If your use case requires proxies I would recommend using a different library.
